Add RPM scripts

diff --git a/icinga-build-package b/icinga-build-package
--- a/icinga-build-package
+++ b/icinga-build-package
@@ -7,8 +7,21 @@ FILES_DEBIAN="$(ls */debian 2>/dev/null)"
 if [ -n "${FILES_SPEC}" ]; then
   echo "Detected RPM source: ${FILES_SPEC}"
   echo
-  #TODO
-  exit 1
+  echo "[ running source build ]"
+  icinga-build-rpm-source
+  if [ $? -ne 0 ]; then
+    echo "[ source build failed! ]"
+    exit 1
+  fi
+  echo "[ source build completed ]"
+  echo
+  echo "[ running binary build ]"
+  icinga-build-rpm-binary
+  if [ $? -ne 0 ]; then
+    echo "[ binary build failed! ]"
+    exit 1
+  fi
+  echo "[ binary build completed ]"
 elif [ -n "${FILES_DEBIAN}" ]; then
   echo "Detected Debian source files: ${FILES_DEBIAN}"
   echo
@@ -28,7 +41,6 @@ elif [ -n "${FILES_DEBIAN}" ]; then
     exit 1
   fi
   echo "[ binary build completed ]"
-  echo
 else
   echo "Could not detect build type!" >&2
   exit 1
